chore: update step 0

diff --git a/.cl/cloudbuild.yaml b/.cl/cloudbuild.yaml
--- a/.cl/cloudbuild.yaml
+++ b/.cl/cloudbuild.yaml
@@ -13,32 +13,20 @@
 # limitations under the License.
 
 steps:
-  # - id: enable-fuse-config
-#     name: 'ubuntu'
-#     entrypoint: bash
-#     args:
-#       - '-c'
-#       - |
-#         apt-get update && apt-get install -y sed
-#         # Check if FUSE device exists
-#         if [ ! -c /dev/fuse ]; then
-#           echo "Error: FUSE device /dev/fuse not found. FUSE might not be available in this environment."
-#           exit 1
-#         fi
-
-#         # Create /etc/fuse.conf if it doesn't exist and populate with default content
-#         if [ ! -f /etc/fuse.conf ]; then
-#           echo "Creating /etc/fuse.conf with default content."
-#           cat <<EOF > /etc/fuse.conf
-# # Set the maximum number of FUSE mounts allowed to non-root users.
-# # The default is 1000.
-# #mount_max = 1000
-
-# # Allow non-root users to specify the 'allow_other' mount option.
-# #user_allow_other
-# EOF
-#         fi
-#         sudo sed -i 's/#user_allow_other/user_allow_other/g' /etc/fuse.conf
+  # Enable fuse config (Linux - assuming Cloud Build environment is Linux-based)
+  - id: enable-fuse-config
+    name: 'ubuntu'
+    entrypoint: bash
+    args:
+      - '-c'
+      - |
+        apt-get update && apt-get install -y --no-install-recommends fuse
+        # Check if FUSE device exists
+        if [ ! -c /dev/fuse ]; then
+          echo "Error: FUSE device /dev/fuse not found. FUSE might not be available in this environment."
+          exit 1
+        fi
+        sudo sed -i 's/#user_allow_other/user_allow_other/g' /etc/fuse.conf
 
   - id: run mysql integration tests
     name: golang:${_VERSION}
